language: python

sudo: False
dist: trusty

python:
    - 2.7
    - 3.6

install:
    - pip install -U pip
    - pip install coveralls pyflakes
    - pip install matplotlib==2.2.4
    - pip install -e .

script: 
    - python runtests.py

after_success: coveralls
